
development:
  adapter: postgresql
  encoding: unicode
  database: myEcommerce_development
  pool: 5
  username: postgres
  password: root
  

test:
  adapter: postgresql
  encoding: unicode
  database: myEcommerce_test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: myEcommerce_production
  pool: 5
  username: postgres
  password: root